version: '3'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file: .env
  django:
    build: ./api
    command: ["python", "manage.py", "runserver", "0.0.0.0:5000"]
    volumes:
      - ./api:/app/api
    ports:
      - "5000:5000"
    depends_on:
      - db
  frontend:
    build: ./frontend
    command: ["npm", "start"]
    volumes:
      - ./frontend:/app/frontend
      - ./frontend/dist:/app/frontend/dist
      - node-modules:/app/frontend/node_modules
    ports:
      - "3000:3000"

volumes:
  node-modules:
  postgres_data: