version: '3'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file: .env
  django:
    build: ./api
    command: ["python", "manage.py", "runserver", "0.0.0.0:5500"]
    volumes:
      - ./api:/app/api
    ports:
      - "5500:5500"
    depends_on:
      - db
  frontend:
    build: ./frontend
    # command:
    #   - ./start-dev.sh
    volumes:
      - ./frontend:/app/frontend
      - ./frontend/dist:/app/frontend/dist
      - ./frontend/node_modules:/app/frontend/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=ture

volumes:
  node-modules:
  postgres_data: