# Generated by Django 3.0.7 on 2020-06-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='ERROR', max_length=32)),
                ('career', models.CharField(default='0', max_length=16)),
                ('duty', models.CharField(default='ERROR', max_length=32)),
                ('location', models.CharField(default='ERROR', max_length=64)),
                ('required_skill', models.CharField(default='ERROR', max_length=128)),
                ('logo', models.CharField(default='ERROR', max_length=64)),
                ('content', models.TextField(default='ERROR')),
            ],
        ),
    ]
